site_name: Pomodoro-Timer開発情報共有
theme:
  name: material
  language: ja
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  favicon: favicon.png
  features:
    - tabs
nav:
  - このサイトについて: index.md
  - 環境準備: 010.initial_settings/index.md
  - チュートリアルについて:
      - フロントエンド: 020.tutorial/010.frontend/index.md
      - バックエンド: 020.tutorial/020.backend/index.md
  - 開発ルール: 
      - 会議体: 030.rule/010.meeting/index.md
      - git運用について: 030.rule/020.git/index.md
      - フロントエンド: 030.rule/030.frontend/index.md
  - 設計書:
      - ユビキタス言語: 040.document/010.ubiquitous_language/index.md
      - DB設計書: 040.document/020.db/index.md
      - API定義: 040.document/030.api/index.md
  - 会議:
      - 2022/03/27: 050.meeting/010.20220327/index.md
      - 2022/04/03: 050.meeting/020.20220403/index.md
  - Tips:
      - git: 999.tips/010.git/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true
  - toc:
      permalink: true
  - attr_list
plugins:
  - render_swagger
copyright: 'Copyright © 2021 - Pomodoro-Timer Application Ltd. Allrights Reserved.'